Contact form feature
codecaiine/contact-form-review pull request #1
Opened 2022-06-22 13:21 UTC by codecaiine

### Add contact form

- Add contact form
- Add form styles in main.css file

2022-06-22 18:10 UTC, BertrandConxy requested changes
Hi  @codecaiine , 

**Good job so far! 🚀**

I really liked your design and your commitment to parse the Figma design. However, there are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃 


## Highlights 🏅 
- All linters are passing
- Good commit messages
- The project works fine
- Use of correct GitHub flow


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@BertrandConxy) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 18:10 UTC, BertrandConxy commented on css/main.css
> +}
- [ ] Again, looking at the design of your form, I realized that it is almost similar to the Figma design given, but you should stick to the design as much as possible. In addition, as a Front-end Developer, attention to all details even the smallest ones is one of the most important abilities to have.
**Figma design**
![image](https://user-images.githubusercontent.com/90222110/175105516-b5d4efa4-cf11-4521-8ba8-055aaad75165.png)

Your Design
![image](https://user-images.githubusercontent.com/90222110/175105649-0672ce44-5793-40c3-b8d9-265aa70973ab.png)
You can observe that there are some improvements that need to be made. Therefore, I would recommend you add them before proceeding to other tasks. You may consider increasing the size of the inputs, their `margin-bottom` and some `padding` to the placeholder and other things which are there in the design. 😺

2022-06-23 17:48 UTC, codecaiine commented on css/main.css
> +
Thank you I'm implementing it.

2022-06-23 17:48 UTC, codecaiine commented on README.md
> +## 🤝 Contributing
Thank you I'm implementing it.

2022-06-23 17:49 UTC, codecaiine commented on README.md
> +
Thank you I'm implementing it.

2022-06-23 18:35 UTC, mwanawabangona requested changes
# Status: Changes Required  
### Hi @codecaiine  :wave:
Wow 👨🏽‍💻 ! You've done an amazing job with this code review! You're rocking and only with minor :pinching_hand:  improvements which you left out, you're ready to launch to space and beyond 🚀 
> 
## Highlights  :medal_sports:

✅  Good utilization of GitHub inline comments feature in the review ✔️  
✅ All linters are passing
✅ Good commit messages
✅ Use of correct GitHub flow

## Required Changes 
Check the comments under the review.
##  Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-06-23 18:35 UTC, mwanawabangona commented on index.html
> +            rel="noreferrer noopener">See project</a>
- [ ] :wave: Kindly add a link to `href` which redirects to the source code. It is imperative that this is done so as to allow potential recruiters to check your Projects at their convenience.

2022-06-28 23:14 UTC, merged